version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '16.6'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - run:
                name: Config git
                command: |
                  git config user.email "gianglevan94@gmail.com"
                  git config user.name "giangg"
            - add_ssh_keys:
                fingerprints:
                  - "1b:b6:40:f9:d8:51:00:48:6b:38:f9:62:02:ab:f1:3f"
            - run: npm run deploy
